title: CCLHM0057 - IHL
logo: LOGO-HISTÓRIA-BA-novo.png
description: História da América - colonização e resistência, 2020.1. prof. Eric Brasil.
show_downloads: true
author: Eric Brasil
google_analytics:
theme: jekyll-theme-slate
